/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    IconMdiArrowLeftTop: typeof import('~icons/mdi/arrow-left-top')['default']
    IconMdiArrowLeftTop1: typeof import('~icons/mdi/arrow-left-top1')['default']
    IconMdiArrowTopBoldBoxOutline: typeof import('~icons/mdi/arrow-top-bold-box-outline')['default']
    IconMdiCalendarMonthOutline: typeof import('~icons/mdi/calendar-month-outline')['default']
    IconMdiCommentOutline: typeof import('~icons/mdi/comment-outline')['default']
    IconMdiDeleteForeverOutline: typeof import('~icons/mdi/delete-forever-outline')['default']
    IconMdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    IconMdiFavoriteBorder: typeof import('~icons/mdi/favorite-border')['default']
    IconMdiFileVideoOutline: typeof import('~icons/mdi/file-video-outline')['default']
    IconMdiFocusField: typeof import('~icons/mdi/focus-field')['default']
    IconMdiFolderOpenOutline: typeof import('~icons/mdi/folder-open-outline')['default']
    IconMdiFormatVerticalAlignTop: typeof import('~icons/mdi/format-vertical-align-top')['default']
    IconMdiHomeAccount: typeof import('~icons/mdi/home-account')['default']
    IconMdiImagePlusOutline: typeof import('~icons/mdi/image-plus-outline')['default']
    IconMdiLinkVariant: typeof import('~icons/mdi/link-variant')['default']
    IconMdiLocationRadiusOutline: typeof import('~icons/mdi/location-radius-outline')['default']
    IconMdiLockOutline: typeof import('~icons/mdi/lock-outline')['default']
    IconMdiLoginVariant: typeof import('~icons/mdi/login-variant')['default']
    IconMdiLogout: typeof import('~icons/mdi/logout')['default']
    IconMdiMusic: typeof import('~icons/mdi/music')['default']
    IconMdiSettingsOutline: typeof import('~icons/mdi/settings-outline')['default']
    IconMdiSquareEditOutline: typeof import('~icons/mdi/square-edit-outline')['default']
    IconMdiTrashCanOutline: typeof import('~icons/mdi/trash-can-outline')['default']
    IconMdiVerified: typeof import('~icons/mdi/verified')['default']
  }
}
